server {
    listen       8443 ssl;
    listen       8443 quic reuseport;

    server_name  _;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_protocols        TLSv1.3;
    # ssl_ciphers          HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  off;


    quic_retry on;
    ssl_early_data off;

    http2 on;
    http3 on;

    ssl_certificate     /etc/nginx/ssl/localhost.crt;
    ssl_certificate_key /etc/nginx/ssl/localhost.key;


    # Enable QUIC + HTTP/3 support
    # add_header Alt-Svc 'h3=":8443"; ma=2592000,h3-29=":8443"; ma=2592000';
    # add_header QUIC-Status $quic;

    location / {
            # required for browsers to direct them to quic port
            add_header alt-svc 'h3=":$server_port"; ma=86400';
            add_header x-quic 'h3';
    }

    location /media {
        aio threads=default;
        alias /usr/share/nginx/html/media;
        try_files $uri =404;
        add_header alt-svc 'h3=":$server_port"; ma=86400';
        add_header x-quic 'h3';
    }
}