server {
    listen       8443 ssl;
    listen       8443 quic reuseport;

    server_name  _;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_protocols        TLSv1.3 TLSv1.2;
    ssl_ciphers          HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;


    quic_retry on;
    ssl_early_data on;

    http2 on;
    http3 on;

    ssl_certificate     /etc/nginx/ssl/localhost.crt;
    ssl_certificate_key /etc/nginx/ssl/localhost.key;
    add_header Alt-Svc 'h3=":8443"; ma=2592000,h3-29=":8443"; ma=2592000';

    location / {
            # required for browsers to direct them to quic port
            add_header Alt-Svc 'h3=":8443"; ma=86400';
    }

    location /media {
        aio threads=default;
        alias /usr/share/nginx/html/media;
        try_files $uri =404;
    }
}